#!/usr/bin/env bash

# The source code of Rust already contains a script for creating tags, but
# if you only want to jump into the standard library then reducing the directories
# gives better results.
# 
# First get the Rust source code:
# 
#     $ git clone https://github.com/rust-lang/rust.git
#     $ cd rust
# 
# And now execute the following script inside of the rust directory:
    
src_dirs=`echo $PWD/src/{liballoc,libarena,libbacktrace,libcollections,libcore,libflate,libfmt_macros,libgetopts,libgraphviz,liblog,librand,librbml,libserialize,libstd,libsyntax,libterm}`
    
ctags -f rusty-tags.vi --options=src/etc/ctags.rust --languages=Rust --recurse $src_dirs
ctags -e -f rusty-tags.emacs --options=src/etc/ctags.rust --languages=Rust --recurse $src_dirs
